# Generated by Django 3.2.3 on 2021-12-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20211216_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserCustom',
        ),
    ]
