# Generated by Django 3.2.3 on 2021-12-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20211220_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='module',
        ),
    ]
